【文档】略微完善README与更漂亮的布局
Wedot-Engine/WeDot pull request #33
Opened 2024-11-05 13:15 UTC by QiNuoTu

部分功能没有多语言支持，在README EN中采用CN作为标注

2024-11-05 16:44 UTC, QiNuoTu commented
> 看一下这个回帖谢谢 [#32 (review)](https://github.com/Wedot-Engine/WeDot/pull/32#pullrequestreview-2415960919) 虽然这个小问题在更新readme那会儿就一直存在了，但稍加细心的人会一眼看出这句话的翻译腔。

哈哈哈啊哈哈哈哈啊哈哈哈哈哈，这个不是我写的，我还以为是刻意这样的：）

2024-11-05 16:59 UTC, QiNuoTu commented
> 看一下这个回帖谢谢 [#32 (review)](https://github.com/Wedot-Engine/WeDot/pull/32#pullrequestreview-2415960919) 虽然这个小问题在更新readme那会儿就一直存在了，但稍加细心的人会一眼看出这句话的翻译腔。

改为【
Wedot 是 Godot 的一个分支，是一个多平台的 2D 和 3D 游戏引擎，使开发者能够专注于游戏本身，让开发者们可以全心投入到游戏的世界里，不用分心去操心那些复杂的技术细节，在技术上 Wedot 将会更符合中国开发者与市场需求。
】如何

2024-11-06 13:53 UTC, PJ-568 commented on README.md
> +WeDot 是 Godot 的一个分支。WeDot 引擎是一个多平台的 2D 和 3D 游戏引擎，专注于技术和用户体验。它设计得易于使用，使开发者能够专注于游戏本身。
```suggestion
WeDot 是一个专注于技术和用户体验的，多平台的 2D、3D 游戏引擎。
WeDot 专注于易用性，能让开发者把注意力集中在游戏开发本身，而非复杂的技术细节。
```

2024-11-06 13:54 UTC, PJ-568 requested changes
Commit message 要符合格式。

2024-11-06 14:44 UTC, closed without merging